"""add_pricing_columns

Revision ID: 0123e9fc6121
Revises: bc5b27a0a852
Create Date: 2026-07-15 22:42:55.183072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0123e9fc6121'
down_revision: Union[str, None] = 'bc5b27a0a852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('extra_guest_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='500'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('extra_guest_price')
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('original_price')

    # ### end Alembic commands ###
