"""Add rejection_reason to bookings

Revision ID: 6ed58d579c48
Revises: 602a219429bf
Create Date: 2026-07-14 17:00:44.915423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed58d579c48'
down_revision: Union[str, None] = '602a219429bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('rejection_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'rejection_reason')
    # ### end Alembic commands ###
