"""add package and budget trip to bookings

Revision ID: bc5b27a0a852
Revises: 6ed58d579c48
Create Date: 2026-07-14 18:10:58.185099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5b27a0a852'
down_revision: Union[str, None] = '6ed58d579c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Safety check: drop the temporary table if it was left behind from a previous failed run
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_bookings')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('budget_trip_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.String(length=200), nullable=True))
        batch_op.alter_column('room_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_bookings_budget_trip_id'), ['budget_trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_package_id'), ['package_id'], unique=False)
        batch_op.create_foreign_key('fk_bookings_budget_trips', 'budget_trips', ['budget_trip_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_bookings_packages', 'packages', ['package_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookings_budget_trips', type_='foreignkey')
        batch_op.drop_constraint('fk_bookings_packages', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bookings_package_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_budget_trip_id'))
        batch_op.alter_column('room_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('item_name')
        batch_op.drop_column('budget_trip_id')
        batch_op.drop_column('package_id')

    # ### end Alembic commands ###
